export enum PermissionName {
  users_create = 'users:create',
  users_read = 'users:read',
  users_update = 'users:update',
  users_delete = 'users:delete',
  users_save = 'users:save',
  stocks_create = 'stocks:create',
  stocks_read = 'stocks:read',
  stocks_update = 'stocks:update',
  stocks_delete = 'stocks:delete',
  stocks_save = 'stocks:save',
  roles_create = 'roles:create',
  roles_read = 'roles:read',
  roles_update = 'roles:update',
  roles_delete = 'roles:delete',
  roles_save = 'roles:save',
  definitions_create = 'definitions:create',
  definitions_read = 'definitions:read',
  definitions_update = 'definitions:update',
  definitions_delete = 'definitions:delete',
  definitions_save = 'definitions:save',
  customers_create = 'customers:create',
  customers_read = 'customers:read',
  customers_update = 'customers:update',
  customers_delete = 'customers:delete',
  customers_save = 'customers:save'
}
