export enum PermissionName {
  users_create = 'users:create',
  users_read = 'users:read',
  users_update = 'users:update',
  users_delete = 'users:delete',
  users_save = 'users:save',
  stocks_create = 'stocks:create',
  stocks_read = 'stocks:read',
  stocks_update = 'stocks:update',
  stocks_delete = 'stocks:delete',
  stocks_save = 'stocks:save',
  roles_create = 'roles:create',
  roles_read = 'roles:read',
  roles_update = 'roles:update',
  roles_delete = 'roles:delete',
  roles_save = 'roles:save',
  seller_sales = 'seller:sales',
  admin_op = 'admin:op',
  company_create = 'company:create'
}
